### PR TITLE
Add windows support

### PR DESCRIPTION
**Pull request by vmuriart**
Added windows support for #7. 
Fixed print statements for Python3 compatibility 
Fixed file write modes*
Removed unneeded dependencies/libraries on install.py and __init__.py

### CODE REVIEW

**Comment by vmuriart** [comment]
@dunovank Thanks for the great work you've done! I did a couple changes to improve compatibility. Don't have a linux/mac to tests against, but the home directory should still work. 

Thanks!

**Comment by dunovank** [comment]
@vmuriart You are the man! Everything checks out on OSX so I'm closing #7 . Thanks!

**Comment by vmuriart** [comment]
No problem. There's a bug w the option to turn on/off the toolbar. I think
it's present before I did any changes, but can't test it on Windows.
For whatever reason the generator doesn't output any lines when being
exhausted. May need to open a diff bug report for it, or write a different
method for it.
Does it still work for you?

**Comment by dunovank** [comment]
Yeah I should have fixed that by now but I'm currently in the throes of dissertation prep. I was actually thinking about eliminating it entirely but given the number of users that appear to rely on it, I think it's probably worth fixing. Feel free to take a crack at it, it's going to be a little while before I have the free time, cognitive resources, and/or energy to mess with it.

**Comment by vmuriart** [comment]
No problems, been there, know the feeling. 
Fixing it would be the best option. though looks like the entire `css` might need refactoring. I tried looking at the sources you mentioned on the `css`, but wasn't able to find everything on them to see how you created it. did you have other references? 

given that `jupyter` is the new name, you ok with making `jupyter` the default instead of `ipython`?

**Comment by dunovank** [comment]
Yeah I agree. And you're right, the css is hideous. I'll see about relocating the block of code for restoring the toolbar and will update you here when I find it. And yes, I like the idea of changing the name to jupyter from ipython. Thanks for all the feedback, man. Been very helpful!

**Pull request merged**
