### PR TITLE
added a solarized-dark theme based on solarized-light

### PR DESCRIPTION
**Pull request by raybuhr**
basically just copied the light theme, flipped the colors for
background (bg) and foreground (fg). I added a screenshot of
my setup using the iRuby jupyter kernel to show how it works.

### CODE REVIEW

**Comment by dunovank** [comment]
Looks great! Would you mind modifying the toolbar to fit with the dark theme? (see example below of toolbar in "onedork" theme)
onedork_toolbarexample

**Comment by dunovank** [comment]
?

**Comment by raybuhr** [comment]
Hey, sorry for delay. I fixed the styling based on your requests, as well as tweaked the menu dropdown to better match the onedork theme. I might have created a problem pushing my changes as it looks like I might have tried to repush changes made since I forked the repo. My only changes should be to the solarized-dark.less file. 
https://github.com/dunovank/jupyter-themes/pull/103/commits/b05c51ace324d756243f0102e46a2d0ca0e59b6c

Let me know if you want me to submit a new PR or if you can still use this one.

**Comment by dunovank** [comment]
Looks good to me, thanks dude!

**Comment by Ktl-XV** [comment]
Hi, just got on the git version to test this out.
When trying to set this theme I get the following errors:
```
E: line: 0: Unknown variable @item-danger
E: line: 0: Unknown variable @item-info
E: line: 0: Unknown variable @item-warning
E: line: 0: Unknown variable @item-success
```
Just started using Jupyter Notebook and this make it much better looking, thanks both.

**Comment by raybuhr** [comment]
Yeah, I got that too when I installed on my work computer. I'll submit the fix asap

**Comment by raybuhr** [comment]
@Ktl-XV I just submitted PR #121 to fix that issue going forward

**Pull request merged**
